OUT=../lua2sexp
CMD=time ruby

all: test

test: $(OUT)

		$(CMD) $(OUT) num.lua

		$(CMD) $(OUT) var.lua	

		$(CMD) $(OUT) mlstr.lua
		$(CMD) $(OUT) long.lua


		$(CMD) $(OUT) forin.lua
		$(CMD) $(OUT) for.lua
		$(CMD) $(OUT) repeat.lua
		$(CMD) $(OUT) while.lua
		$(CMD) $(OUT) do.lua

		$(CMD) $(OUT) local.lua

		$(CMD) $(OUT) bool.lua

		$(CMD) $(OUT) unops.lua
		$(CMD) $(OUT) ops.lua

		$(CMD) $(OUT) lcomment.lua
		$(CMD) $(OUT) comment.lua

		$(CMD) $(OUT) table3.lua
		$(CMD) $(OUT) lstr.lua
		$(CMD) $(OUT) nstr.lua

		$(CMD) $(OUT) elseif.lua
		$(CMD) $(OUT) ifthen.lua

		$(CMD) $(OUT) dot3f.lua
		$(CMD) $(OUT) table2.lua
		$(CMD) $(OUT) table1.lua
		$(CMD) $(OUT) dot3.lua
		$(CMD) $(OUT) func2.lua
		$(CMD) $(OUT) func.lua

		$(CMD) $(OUT) empty.lua
		$(CMD) $(OUT) mini.lua
		$(CMD) $(OUT) ret.lua
		$(CMD) $(OUT) semi.lua

		$(CMD) $(OUT) lumino.lua
